// gateinitiative CLI: help output

import { C, banner } from './context.mjs';

export function showHelp() {
  banner();
  console.log(`  ${C.bold}Usage:${C.reset}`);
  console.log(`    gateinitiative ${C.green}start${C.reset}    [--mode strict|warn|audit] [--root <path>] [--shadow-dir <path>] [--register] [--no-toast]`);
  console.log(`    gateinitiative ${C.green}stop${C.reset}     [--root <path>]`);
  console.log(`    gateinitiative ${C.green}restart${C.reset}  [--mode strict|warn|audit] [--root <path>] [--shadow-dir <path>] [--no-toast]`);
  console.log(`    gateinitiative ${C.green}status${C.reset}   [--root <path>]`);
  console.log(`    gateinitiative ${C.cyan}watch${C.reset}    [--mode strict|warn|audit] [--root <path>] [--shadow-dir <path>] [--max-file-bytes N] [--no-startup-scan] [--no-toast] [--verbose] [--sound]`);
  console.log(`    gateinitiative ${C.cyan}check${C.reset}    [--root <path>] [--shadow-dir <path>] [--max-file-bytes N] [--no-toast]`);
  console.log(`    gateinitiative ${C.cyan}test${C.reset}      [--root <path>]`);
  console.log(`    gateinitiative ${C.cyan}context${C.reset}    [--file <path>] [--root <path>]`);
  console.log(`    gateinitiative ${C.cyan}init${C.reset}       [--root <path>]`);
  console.log(`    gateinitiative ${C.cyan}trust${C.reset}      [--root <path>] [--shadow-dir <path>]`);
  console.log(`    gateinitiative ${C.cyan}onboard${C.reset}    [--yes] [--dry-run] [--root <path>]`);
  console.log(`    gateinitiative ${C.cyan}list${C.reset}       [--root <path>]`);
  console.log(`    gateinitiative ${C.cyan}bridge${C.reset}     [--once] [--ide zed,void,cursor] [--max-docs N]`);
  console.log(`    gateinitiative ${C.cyan}doctor${C.reset}    [--root <path>] [--shadow-dir <path>] [--no-toast]`);
  console.log(`    gateinitiative ${C.cyan}clean${C.reset}     [--delete]`);
  console.log(`    gateinitiative ${C.cyan}review${C.reset}    [list|approve <id>|delete <id>|clear] [--shadow-dir <path>] [--session] [--for N]`);
  console.log(`    gateinitiative ${C.cyan}quarantine${C.reset} [list|show <id>|restore <id>|delete <id>] [--root <path>]`);
  console.log('');
  console.log(`  ${C.bold}Daemon Lifecycle:${C.reset}`);
  console.log(`    ${C.green}start${C.reset}     Start gateINITIATIVE as a background daemon`);
  console.log(`    ${C.green}stop${C.reset}      Stop the running daemon`);
  console.log(`    ${C.green}restart${C.reset}   Restart the daemon (stop + start)`);
  console.log(`    ${C.green}status${C.reset}    Show daemon status (PID, uptime, mode)`);
  console.log('');
  console.log(`  ${C.bold}Commands:${C.reset}`);
  console.log(`    ${C.cyan}watch${C.reset}     Start the filesystem watcher (foreground, for debugging)`);
  console.log(`    ${C.cyan}check${C.reset}       One-shot gate evaluation (exits with code 1 on violations)`);
  console.log(`    ${C.cyan}test${C.reset}        Run pass/fail fixtures for each loaded gate`);
  console.log(`    ${C.cyan}context${C.reset}     Show context recommendations for a file or list all rules`);
  console.log(`    ${C.cyan}init${C.reset}        Create a starter .gates.yml with example gates`);
  console.log(`    ${C.cyan}trust${C.reset}       Trust the current gate sources for block enforcement`);
  console.log(`    ${C.cyan}onboard${C.reset}     Scan project + instruction files, generate gates/profile/rules`);
  console.log(`    ${C.cyan}list${C.reset}        Show all loaded gates and their trigger patterns`);
  console.log(`    ${C.cyan}bridge${C.reset}      Generate lean IDE rules from context signals`);
  console.log(`    ${C.cyan}doctor${C.reset}     Run self-diagnostics on gates, playbooks, and data dirs`);
  console.log(`    ${C.cyan}clean${C.reset}      List orphaned external data dirs (use --delete to remove)`);
  console.log(`    ${C.cyan}review${C.reset}     Approve or delete pending enforcement decisions`);
  console.log(`    ${C.cyan}quarantine${C.reset}  Inspect or restore files moved to quarantine by strict mode`);
  console.log('');
  console.log(`  ${C.bold}Bridge Options:${C.reset}`);
  console.log(`    ${C.gray}--once${C.reset}          One-shot: generate rules and exit`);
  console.log(`    ${C.gray}--ide <list>${C.reset}    Comma-separated IDE targets (default: zed,void,cursor)`);
  console.log(`    ${C.gray}--max-docs N${C.reset}    Max context docs to inline (default: 2)`);
  console.log(`    ${C.gray}--max-chars N${C.reset}   Max chars per inlined doc (default: 2000)`);
  console.log(`    ${C.gray}--no-state${C.reset}      Exclude playbook state summary`);
  console.log(`    ${C.gray}--no-toast${C.reset}     Suppress OS toast notifications`);
  console.log('');
  console.log(`  ${C.bold}Daemon Options:${C.reset}`);
  console.log(`    ${C.gray}--register${C.reset}    Print platform-specific boot-persistence instructions (start only)`);
  console.log('');

  console.log(`  ${C.bold}Enforcement Modes:${C.reset}`);
  console.log(`    ${C.red}strict${C.reset}  Revert files on block-severity violations (shadow copy)`);
  console.log(`    ${C.yellow}warn${C.reset}    Alert only (default) — never modifies files`);
  console.log(`    ${C.gray}audit${C.reset}   Silent logging — writes to .gateinitiative/violations.log`);
  console.log('');
  console.log(`  ${C.bold}Watch Mode Features:${C.reset}`);
  console.log(`    • ${C.red}Gate enforcement${C.reset}      ${C.gray}Detect violations in real-time${C.reset}`);
  console.log(`    • ${C.cyan}Context detection${C.reset}    ${C.gray}Recommend which docs/agents/ to load${C.reset}`);
  console.log(`    • ${C.gray}--no-context${C.reset}         ${C.gray}Disable context signals (gates only)${C.reset}`);
  console.log(`    • ${C.gray}--enforce-context${C.reset}    ${C.gray}Enforce rules with enforce:true via playbook-state${C.reset}`);
  console.log(`    • ${C.gray}--enforce-context-all${C.reset} ${C.gray}Enforce ALL context rules (not just enforce:true)${C.reset}`);
  console.log('');
  console.log(`  ${C.bold}Gate Sources (checked in order):${C.reset}`);
  console.log(`    1. docs/agents/*.md   ${C.gray}(embedded \`\`\`gate blocks)${C.reset}`);
  console.log(`    2. .gates/ directory  ${C.gray}(dedicated gate files)${C.reset}`);
  console.log(`    3. .gates.yml         ${C.gray}(project root)${C.reset}`);
  console.log('');
  console.log(`  ${C.bold}Context Signal Output:${C.reset}`);
  console.log(`    • Terminal            ${C.gray}(real-time LOAD recommendations)${C.reset}`);
  console.log(`    • .gateinitiative/context.json  ${C.gray}(machine-readable, for IDE extensions)${C.reset}`);
  console.log('');
  console.log(`  ${C.bold}Trigger Points:${C.reset}`);
  console.log(`    • Filesystem events  ${C.gray}(file create, modify — via chokidar)${C.reset}`);
  console.log(`    • One-shot CLI       ${C.gray}(gateinit check / context — for CI/scripts)${C.reset}`);
  console.log(`    • Any automation     ${C.gray}(cron, task scheduler, npm scripts)${C.reset}`);
  console.log('');
}
