// gateinitiative: Playbook Bridge
//
// Bridges gateinitiative's context detection and playbook enforcement into
// IDE rules files. Instead of shipping a 37K-token monolithic system prompt,
// this module generates a focused ~300-800 token rules file containing only
// the playbook instructions relevant to the current task.
//
// Architecture:
//   context.json  ──→  PlaybookBridge  ──→  .zed/rules/active-playbook.md
//   .playbooks/*.yaml                     .voidrules
//   playbook-state.json                   .cursor/rules/active.mdc
//
// The bridge runs as a lightweight companion process alongside gateinitiative.
// It watches context.json (written by gateinitiative's watcher) and regenerates
// the IDE rules file whenever the developer's focus shifts.
//
// Output is designed to REPLACE the IDE's built-in system prompt (when
// disableSystemMessage=true in Void, or via agent profiles in Zed).

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { createHash } from 'node:crypto';
import { getDecisions } from './decisions.mjs';

/**
 * @typedef {Object} BridgeConfig
 * @property {string} projectRoot - Project root path
 * @property {string[]} [ideTargets] - Which IDE rules files to write
 * @property {number} [debounceMs] - Debounce window for regenerating rules
 * @property {number} [maxContextDocs] - Max context docs to inline (default: 2)
 * @property {number} [maxDocChars] - Max chars per inlined doc (default: 2000)
 * @property {boolean} [includePlaybookState] - Include recent state summary
 * @property {string} [shadowDir] - External data dir override for pending decisions
 * @property {Array} [gates] - Loaded gates to surface in rules (2.1)
 * @property {Array} [lastViolations] - Recent violations to inject as feedback (2.2)
 * @property {boolean} [daemonRunning] - Whether daemon is currently running (2.4)
 * @property {number|null} [daemonStaleSeconds] - Seconds since last heartbeat, if known
 */

const DEFAULT_CONFIG = {
  ideTargets: ['zed', 'void', 'cursor'],
  debounceMs: 1000,
  maxContextDocs: 2,
  maxDocChars: 2000,
  includePlaybookState: true,
};

// Marker proving a rules file was generated by this bridge. Files without it
// are user-owned and must never be overwritten.
export const GENERATED_MARKER = '<!-- generated-by: gateinitiative-bridge -->';

// IDE-specific output paths and formats
const IDE_FORMATS = {
  zed: {
    // Zed reads `.rules` at the worktree root (also honors .cursorrules etc.)
    path: '.rules',
    format: 'markdown',
    wrap: (content) => content,
  },
  void: {
    path: '.voidrules',
    format: 'markdown',
    wrap: (content) => content,
  },
  cursor: {
    path: '.cursor/rules/active-playbook.mdc',
    format: 'mdc',
    wrap: (content) => [
      '---',
      'description: Active playbook instructions (auto-generated by gateinit bridge)',
      'globs:',
      'alwaysApply: true',
      '---',
      '',
      content,
    ].join('\n'),
  },
};

/**
 * Load and parse context.json produced by gateinitiative's watcher
 * @param {string} projectRoot
 * @returns {Promise<{signals: Array, timestamp: string}|null>}
 */
async function loadContextSignals(projectRoot) {
  try {
    const raw = await readFile(
      join(projectRoot, '.gateinitiative', 'context.json'),
      'utf-8'
    );
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

/**
 * Load playbook state (recent read/edit history)
 * @param {string} projectRoot
 * @returns {Promise<Object>}
 */
async function loadPlaybookState(projectRoot) {
  try {
    const raw = await readFile(
      join(projectRoot, '.gateinitiative', 'playbook-state.json'),
      'utf-8'
    );
    return JSON.parse(raw);
  } catch {
    return { session: null, completed: {} };
  }
}

/**
 * Load pending review decisions and active overrides.
 * @param {string} projectRoot
 * @param {string} [shadowDir]
 * @returns {Promise<{pending: Array, overrides: Array}>}
 */
async function loadPendingDecisions(projectRoot, shadowDir) {
  try {
    return await getDecisions(projectRoot, shadowDir);
  } catch {
    return { pending: [], overrides: [] };
  }
}

/**
 * Load recent violations written by the Enforcer.
 * @param {string} projectRoot
 * @returns {Promise<Array>}
 */
async function loadLastViolations(projectRoot) {
  try {
    const raw = await readFile(
      join(projectRoot, '.gateinitiative', 'last-violations.json'),
      'utf-8'
    );
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) return parsed;
    if (parsed && Array.isArray(parsed.violations)) return parsed.violations;
    return [];
  } catch {
    return [];
  }
}

/**
 * Escape content so it cannot break out of a markdown code fence.
 * Uses quadruple-backtick outer fences and neutralises runs of backticks.
 * @param {string} text
 * @returns {string}
 */
function escapeCodeFences(text) {
  // Break any run of 3+ backticks by inserting a zero-width space after the first.
  return text.replace(/```+/g, (match) => '\u200b' + match.slice(1));
}

/**
 * Summarize recent activity from playbook state for the rules file.
 * Only includes the most recent reads/edits to keep token count low.
 * @param {Object} state - playbook-state.json contents
 * @param {number} maxEntries - Maximum entries to include
 * @returns {string}
 */
function summarizeState(state, maxEntries = 10) {
  if (!state.completed || Object.keys(state.completed).length === 0) {
    return '';
  }

  // Sort by timestamp descending, take most recent
  const entries = Object.entries(state.completed)
    .sort(([, a], [, b]) => b - a)
    .slice(0, maxEntries);

  const reads = entries
    .filter(([k]) => k.startsWith('read:'))
    .map(([k]) => k.replace('read:', ''));

  const edits = entries
    .filter(([k]) => k.startsWith('edit:'))
    .map(([k]) => k.replace('edit:', ''));

  const checks = entries
    .filter(([k]) =>
      k.startsWith('lint:') || k.startsWith('tests:') || k.startsWith('typecheck:')
    )
    .map(([k]) => k);

  const parts = [];
  if (reads.length > 0) {
    parts.push(`Recently read: ${reads.slice(0, 5).join(', ')}`);
  }
  if (edits.length > 0) {
    parts.push(`Recently edited: ${edits.slice(0, 3).join(', ')}`);
  }
  if (checks.length > 0) {
    parts.push(`Checks passed: ${checks.join(', ')}`);
  }

  return parts.join('\n');
}

/**
 * Try to read and truncate a context doc for inlining
 * @param {string} projectRoot
 * @param {string} docPath - Relative path to the doc
 * @param {number} maxChars - Maximum characters to include
 * @returns {Promise<string|null>}
 */
async function loadContextDoc(projectRoot, docPath, maxChars) {
  try {
    const content = await readFile(join(projectRoot, docPath), 'utf-8');
    if (content.length <= maxChars) return content;

    // Truncate at a paragraph boundary if possible
    const truncated = content.slice(0, maxChars);
    const lastParagraph = truncated.lastIndexOf('\n\n');
    if (lastParagraph > maxChars * 0.7) {
      return truncated.slice(0, lastParagraph) + '\n\n[... truncated — read the full file for complete reference]';
    }
    return truncated + '\n\n[... truncated]';
  } catch {
    return null;
  }
}

/**
 * Build the lean rules content from context signals and playbooks
 * @param {BridgeConfig} config
 * @returns {Promise<string>} - The rules content
 */
export async function buildRulesContent(config) {
  const {
    projectRoot,
    maxContextDocs,
    maxDocChars,
    includePlaybookState,
    shadowDir,
    daemonRunning = true,
    daemonStaleSeconds = null,
  } = config;

  const contextData = await loadContextSignals(projectRoot);
  const state = await loadPlaybookState(projectRoot);
  const signals = contextData?.signals || [];
  const lastViolations = config.lastViolations || await loadLastViolations(projectRoot);
  const gates = config.gates || [];
  const { pending: pendingDecisions, overrides: activeOverrides } = await loadPendingDecisions(projectRoot, shadowDir);

  // ── Build the rules document ──────────────────────────────────────────

  const sections = [];

  // 1. Header — minimal identity (replaces IDE's built-in system prompt)
  sections.push(
    GENERATED_MARKER,
    '# Active Context',
    '',
    `Generated: ${new Date().toISOString()}`,
    `Source: gateinit bridge`,
  );

  // 2. Daemon status banner — fail-open visibility (2.4)
  if (!daemonRunning) {
    sections.push(
      '',
      '⚠ **gateinitiative daemon is NOT RUNNING.** These rules are unenforced until the daemon starts.',
      'Run `gateinit start` to enable live enforcement.',
    );
  } else if (daemonStaleSeconds !== null && daemonStaleSeconds > 30) {
    sections.push(
      '',
      `⚠ **gateinitiative daemon heartbeat is stale** (${Math.round(daemonStaleSeconds)}s ago). Rules may be unenforced.`,
      'Check `gateinit status` or restart the daemon.',
    );
  }

  // 2. Active focus — what the developer is currently working on
  if (signals.length > 0) {
    sections.push('', '## Current Focus', '');
    for (const signal of signals.slice(0, 3)) {
      sections.push(
        `- **${signal.contextFile}**: ${signal.reason}`,
      );
    }
  }

  // 3. Enforced gates — make rules visible so agents avoid them (2.1)
  if (gates.length > 0) {
    sections.push('', '## Enforced Gates', '');
    sections.push('These gates are actively enforced on the project:');
    sections.push('');
    for (const gate of gates) {
      const trigger = Array.isArray(gate.trigger) ? gate.trigger.join(', ') : gate.trigger;
      sections.push(`- **${gate.id}** (${gate.severity}) — ${trigger}`);
      sections.push(`  ${gate.message}`);
      if (gate.pattern) sections.push(`  pattern: \`${gate.pattern}\``);
      if (gate.antipattern) sections.push(`  required: \`${gate.antipattern}\``);
    }
  }

  // 4. Context docs — inline the most relevant documentation
  const topSignals = signals.slice(0, maxContextDocs);
  if (topSignals.length > 0) {
    sections.push('', '## Reference Documents', '');

    for (const signal of topSignals) {
      const doc = await loadContextDoc(projectRoot, signal.contextFile, maxDocChars);
      if (doc) {
        const safe = escapeCodeFences(doc);
        sections.push(
          `### ${signal.contextFile}`,
          '',
          '````',
          safe,
          '````',
          '',
        );
      }
    }
  }

  // 4. Recent activity summary — gives the model awareness of prior work
  if (includePlaybookState) {
    const summary = summarizeState(state);
    if (summary) {
      sections.push('', '## Recent Activity', '', summary);
    }
  }

  // 5. Active playbooks — which enforcement rules are currently in scope
  // (loaded from .playbooks/*.yaml by the PlaybookEnforcer)
  try {
    const { loadPlaybooks, findApplicablePlaybook } = await import('./playbook.mjs');
    const playbooks = await loadPlaybooks(projectRoot);
    if (playbooks.length > 0) {
      sections.push('', '## Active Playbook Constraints', '');
      sections.push(
        'These prerequisites MUST be met before editing governed files:',
        '',
      );
      for (const pb of playbooks) {
        const triggers = Array.isArray(pb.trigger) ? pb.trigger.join(', ') : pb.trigger;
        sections.push(`- **${pb.name}**: ${pb.description}`);
        sections.push(`  Files: \`${triggers}\``);
        for (const prereq of pb.prerequisites) {
          sections.push(`  - ${prereq.id}: ${prereq.message} (severity: ${prereq.severity})`);
        }
      }
    }
  } catch {
    // playbook module may not be available
  }

  // 6. Recent violations — feedback loop so agents know a revert happened (2.2)
  if (lastViolations.length > 0) {
    sections.push('', '## Recent Violations', '');
    sections.push('Your last writes were rejected by gateinitiative. Correct these patterns before retrying:');
    sections.push('');
    for (const v of lastViolations.slice(-5).reverse()) {
      const action = v.reverted ? 'REVERTED' : 'BLOCKED';
      sections.push(`- **${action}** ` + "`" + v.file + "`" + ` — ${v.gateId}: ${v.message}`);
    }
  }

  // 7. Pending review decisions — surface human overrides to the agent (2A.6)
  if (pendingDecisions.length > 0 || activeOverrides.length > 0) {
    sections.push('', '## Pending Review Decisions', '');
    if (activeOverrides.length > 0) {
      sections.push('Active overrides (file edits allowed until the override expires):');
      sections.push('');
      for (const o of activeOverrides) {
        const scope = o.expires ? `expires ${new Date(o.expires).toISOString()}` : `scope: ${o.scope}`;
        sections.push(`- **${o.gateId}** on \`${o.file}\` — ${scope}`);
      }
      sections.push('');
    }
    if (pendingDecisions.length > 0) {
      sections.push('Files blocked until a human reviews and approves an override:');
      sections.push('');
      for (const d of pendingDecisions) {
        sections.push(`- **${d.gateId}** on \`${d.file}\`: ${d.reason}`);
      }
    }
  }

  // 8. Footer — instruction to the model
  sections.push(
    '',
    '---',
    '',
    'These instructions were dynamically generated based on your current work.',
    'gateINITIATIVE daemon is enforcing these rules at the filesystem level.',
    'Violations will be caught and reported.',
  );

  return sections.join('\n');
}

/**
 * Write rules content to all configured IDE targets.
 * Refuses to overwrite files it did not generate (missing marker),
 * so a hand-written .rules / .voidrules is never clobbered.
 * @param {string} projectRoot
 * @param {string} content - The rules content
 * @param {string[]} targets - IDE target names
 * @returns {Promise<{written: string[], skipped: string[]}>}
 */
export async function writeRulesToIDEs(projectRoot, content, targets) {
  const written = [];
  const skipped = [];

  for (const target of targets) {
    const format = IDE_FORMATS[target];
    if (!format) continue;

    const fullPath = join(projectRoot, format.path);
    const wrappedContent = format.wrap(content);

    try {
      let existing = null;
      try {
        existing = await readFile(fullPath, 'utf-8');
      } catch { /* doesn't exist yet — safe to create */ }

      if (existing !== null && !existing.includes(GENERATED_MARKER)) {
        skipped.push(format.path);
        continue;
      }

      await mkdir(dirname(fullPath), { recursive: true });
      await writeFile(fullPath, wrappedContent, 'utf-8');
      written.push(format.path);
    } catch {
      // Non-fatal — IDE might not be configured
    }
  }

  return { written, skipped };
}

/**
 * PlaybookBridge — main class for the bridge daemon.
 * Watches .gateinitiative/context.json and regenerates IDE rules on change.
 */
export class PlaybookBridge {
  #config;
  #debounceTimer = null;
  #lastHash = '';

  /**
   * @param {Partial<BridgeConfig> & { projectRoot: string }} config
   */
  constructor(config) {
    // Strip undefined values: `{ maxDocChars: undefined }` must fall back to
    // the default, not disable truncation (slice(0, undefined) = whole doc).
    const defined = Object.fromEntries(
      Object.entries(config).filter(([, v]) => v !== undefined)
    );
    this.#config = { ...DEFAULT_CONFIG, ...defined };
  }

  /**
   * Run a single bridge cycle: read signals → build rules → write to IDEs
   * @returns {Promise<{written: string[], skipped: string[], tokenEstimate: number}>}
   */
  async run(overrides = {}) {
    const config = { ...this.#config, ...overrides };
    const content = await buildRulesContent(config);

    // Dedup: skip write if content hasn't changed
    // (the Generated timestamp line is excluded, or the hash would never match)
    const hash = sha1Hash(content.replace(/^Generated: .*$/m, ''));
    if (hash === this.#lastHash) {
      return { written: [], skipped: [], tokenEstimate: estimateTokens(content) };
    }
    this.#lastHash = hash;

    const { written, skipped } = await writeRulesToIDEs(
      config.projectRoot,
      content,
      config.ideTargets,
    );

    return { written, skipped, tokenEstimate: estimateTokens(content) };
  }

  /**
   * Start watching context.json for changes
   * @returns {Promise<import('chokidar').FSWatcher>}
   */
  async watch() {
    const { watch } = await import('chokidar');
    const contextPath = join(
      this.#config.projectRoot,
      '.gateinitiative',
      'context.json',
    );

    const watcher = watch(contextPath, {
      persistent: true,
      ignoreInitial: false,
      awaitWriteFinish: { stabilityThreshold: 300 },
    });

    watcher.on('change', () => {
      clearTimeout(this.#debounceTimer);
      this.#debounceTimer = setTimeout(() => this.run(), this.#config.debounceMs);
    });

    // Initial run
    await this.run();

    return watcher;
  }

  get config() {
    return { ...this.#config };
  }
}

// ── Utilities ────────────────────────────────────────────────────────────────

function sha1Hash(str) {
  return createHash('sha1').update(str).digest('hex');
}

function estimateTokens(content) {
  // Rough estimate: 1 token ≈ 4 chars for English text
  return Math.round(content.length / 4);
}
